[workspace]
resolver = "2"
members = [
    "crates/gnrs-test-core",
    "crates/gnrs-test-pbt",
    "crates/gnrs-test-fuzz",
    "crates/gnrs-test-pbt-derive",
    "crates/gnrs-test-bench",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ginokent/gnrs-test"
rust-version = "1.82"

[workspace.lints.rust]
unsafe_code = "forbid"
